In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced
from sklearn.preprocessing import LabelEncoder

# Read the CSV and Perform Basic Data Cleaning

In [4]:
# https://help.lendingclub.com/hc/en-us/articles/215488038-What-do-the-different-Note-statuses-mean-

columns = [
    "loan_amnt", "int_rate", "installment", "home_ownership",
    "annual_inc", "verification_status", "issue_d", "loan_status",
    "pymnt_plan", "dti", "delinq_2yrs", "inq_last_6mths",
    "open_acc", "pub_rec", "revol_bal", "total_acc",
    "initial_list_status", "out_prncp", "out_prncp_inv", "total_pymnt",
    "total_pymnt_inv", "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
    "recoveries", "collection_recovery_fee", "last_pymnt_amnt", "next_pymnt_d",
    "collections_12_mths_ex_med", "policy_code", "application_type", "acc_now_delinq",
    "tot_coll_amt", "tot_cur_bal", "open_acc_6m", "open_act_il",
    "open_il_12m", "open_il_24m", "mths_since_rcnt_il", "total_bal_il",
    "il_util", "open_rv_12m", "open_rv_24m", "max_bal_bc",
    "all_util", "total_rev_hi_lim", "inq_fi", "total_cu_tl",
    "inq_last_12m", "acc_open_past_24mths", "avg_cur_bal", "bc_open_to_buy",
    "bc_util", "chargeoff_within_12_mths", "delinq_amnt", "mo_sin_old_il_acct",
    "mo_sin_old_rev_tl_op", "mo_sin_rcnt_rev_tl_op", "mo_sin_rcnt_tl", "mort_acc",
    "mths_since_recent_bc", "mths_since_recent_inq", "num_accts_ever_120_pd", "num_actv_bc_tl",
    "num_actv_rev_tl", "num_bc_sats", "num_bc_tl", "num_il_tl",
    "num_op_rev_tl", "num_rev_accts", "num_rev_tl_bal_gt_0",
    "num_sats", "num_tl_120dpd_2m", "num_tl_30dpd", "num_tl_90g_dpd_24m",
    "num_tl_op_past_12m", "pct_tl_nvr_dlq", "percent_bc_gt_75", "pub_rec_bankruptcies",
    "tax_liens", "tot_hi_cred_lim", "total_bal_ex_mort", "total_bc_limit",
    "total_il_high_credit_limit", "hardship_flag", "debt_settlement_flag"
]

target = ["loan_status"]

In [5]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv.zip')
df = pd.read_csv(file_path, skiprows=1)[:-2]
df = df.loc[:, columns].copy()

# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')

# Drop the null rows
df = df.dropna()

# Remove the `Issued` loan status
issued_mask = df['loan_status'] != 'Issued'
df = df.loc[issued_mask]

# convert interest rate to numerical
df['int_rate'] = df['int_rate'].str.replace('%', '')
df['int_rate'] = df['int_rate'].astype('float') / 100


# Convert the target column values to low_risk and high_risk based on their values
x = {'Current': 'low_risk'}   
df = df.replace(x)

x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    
df = df.replace(x)

df.reset_index(inplace=True, drop=True)

df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

In [6]:
le = LabelEncoder()

le.fit(df["pymnt_plan"])
df["pymnt_plan"] = le.transform(df["pymnt_plan"])

le.fit(df["hardship_flag"])
df["hardship_flag"] = le.transform(df["hardship_flag"])

le.fit(df["debt_settlement_flag"])
df["debt_settlement_flag"] = le.transform(df["debt_settlement_flag"])

In [7]:
df = pd.get_dummies(df, columns=['verification_status', 'issue_d', 'next_pymnt_d', 'initial_list_status', 'application_type', 'home_ownership'])
df.head()

,loan_amnt,int_rate,installment,annual_inc,loan_status,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,open_acc,...,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT
0,10500.0,0.1719,375.35,66000.0,low_risk,0,27.24,0.0,0.0,8.0,...,0,1,0,1,1,0,0,0,0,1
1,25000.0,0.2000,929.09,105000.0,low_risk,0,20.23,0.0,0.0,17.0,...,0,1,0,1,1,0,0,1,0,0
2,20000.0,0.2000,529.88,56000.0,low_risk,0,24.26,0.0,0.0,8.0,...,0,1,0,1,1,0,0,1,0,0
3,10000.0,0.1640,353.55,92000.0,low_risk,0,31.44,0.0,1.0,10.0,...,0,1,0,1,1,0,0,0,0,1
4,22000.0,0.1474,520.39,52000.0,low_risk,0,18.76,0.0,1.0,14.0,...,0,1,0,1,1,0,0,1,0,0

# Split the Data into Training and Testing

In [8]:
# Create our features

X = df.drop(columns='loan_status')

# Create our target
y = df['loan_status']

In [9]:
X.describe()

,loan_amnt,int_rate,installment,annual_inc,pymnt_plan,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,...,next_pymnt_d_Apr-2019,next_pymnt_d_May-2019,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_OWN,home_ownership_RENT
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.0,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000
mean,16677.594562,0.127718,480.652863,8.821371e+04,0.0,21.778153,0.217766,0.497697,12.587340,0.126030,...,0.383161,0.616839,0.123879,0.876121,0.860340,0.139660,0.009285,0.526309,0.106747,0.357659
std,10277.348590,0.048130,288.062432,1.155800e+05,0.0,20.199244,0.718367,0.758122,6.022869,0.336797,...,0.486161,0.486161,0.329446,0.329446,0.346637,0.346637,0.095914,0.499311,0.308793,0.479314
min,1000.000000,0.060000,30.890000,4.000000e+01,0.0,0.000000,0.000000,0.000000,2.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,9000.000000,0.088100,265.730000,5.000000e+04,0.0,13.890000,0.000000,0.000000,8.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,15000.000000,0.118000,404.560000,7.300000e+04,0.0,19.760000,0.000000,0.000000,11.000000,0.000000,...,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,24000.000000,0.155700,648.100000,1.040000e+05,0.0,26.660000,0.000000,1.000000,16.000000,0.000000,...,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000
max,40000.000000,0.308400,1676.230000,8.797500e+06,0.0,999.000000,18.000000,5.000000,72.000000,4.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
# Check the balance of our target values
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [11]:
# Split the X and y into X_train, X_test, y_train, y_test
# YOUR CODE HERE

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=1)

# Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble AdaBoost classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Print the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier onely, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [12]:
# Resample the training data with the RandomOversampler
# YOUR CODE HERE
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=1)

rf_model = rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

In [13]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

balanced_accuracy_score(y_test, rf_pred)

0.683080618047773

In [14]:
# Display the confusion matrix
# YOUR CODE HERE

confusion_matrix(y_test, rf_pred)

array([[   37,    64],
       [    3, 17101]], dtype=int64)

In [15]:
# Print the imbalanced classification report
# YOUR CODE HERE

print(classification_report_imbalanced(y_test, rf_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.93      0.37      1.00      0.52      0.61      0.34       101
   low_risk       1.00      1.00      0.37      1.00      0.61      0.39     17104

avg / total       1.00      1.00      0.37      1.00      0.61      0.39     17205

In [16]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE

importances = rf_model.feature_importances_

importances_sorted = sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

importances_sorted

[(0.0746339307451988, 'last_pymnt_amnt'),
 (0.06588961874403511, 'total_rec_int'),
 (0.064627934132408, 'total_pymnt_inv'),
 (0.05764605047741123, 'total_pymnt'),
 (0.05466690326390639, 'total_rec_prncp'),
 (0.021033178682854755, 'installment'),
 (0.02075291393910477, 'out_prncp_inv'),
 (0.019542906795960643, 'out_prncp'),
 (0.017798620570212954, 'dti'),
 (0.015945957729566387, 'total_bal_ex_mort'),
 (0.01563292651604329, 'mo_sin_old_il_acct'),
 (0.015537370738450244, 'revol_bal'),
 (0.015479966755368509, 'loan_amnt'),
 (0.015339146622797815, 'mo_sin_old_rev_tl_op'),
 (0.015167404769637542, 'max_bal_bc'),
 (0.014390339094948792, 'avg_cur_bal'),
 (0.01397064744961816, 'total_rev_hi_lim'),
 (0.013701346260422737, 'total_il_high_credit_limit'),
 (0.013625337686047482, 'int_rate'),
 (0.013530055142437637, 'total_bc_limit'),
 (0.013519112108687238, 'bc_util'),
 (0.013433636109167925, 'bc_open_to_buy'),
 (0.013236114916745067, 'tot_cur_bal'),
 (0.012885656954977811, 'tot_hi_cred_lim'),
 (0.012510557177086873, 'total_rec_late_fee'),
 (0.012381803950645653, 'total_bal_il'),
 (0.01237366741585392, 'annual_inc'),
 (0.012241448678776181, 'mths_since_rcnt_il'),
 (0.01212911250976247, 'total_acc'),
 (0.011621644816405452, 'il_util'),
 (0.011400518975838525, 'all_util'),
 (0.010901426687934267, 'mths_since_recent_inq'),
 (0.010762880268693386, 'num_il_tl'),
 (0.010711945911944777, 'mths_since_recent_bc'),
 (0.01047128023564493, 'num_rev_accts'),
 (0.009615484357614862, 'acc_open_past_24mths'),
 (0.008902456907342666, 'num_bc_tl'),
 (0.008878672515674703, 'mo_sin_rcnt_tl'),
 (0.00887053358610326, 'num_sats'),
 (0.008841119507739923, 'open_acc'),
 (0.00881742049663452, 'issue_d_Mar-2019'),
 (0.008727899321064266, 'mo_sin_rcnt_rev_tl_op'),
 (0.008525947431674782, 'total_cu_tl'),
 (0.008481260395596307, 'num_op_rev_tl'),
 (0.008292483022973132, 'num_actv_rev_tl'),
 (0.008209754986172222, 'inq_last_12m'),
 (0.008168065810840262, 'num_actv_bc_tl'),
 (0.00800775178199535, 'open_rv_24m'),
 (0.007991037012892565, 'open_il_24m'),
 (0.0075278275697021, 'num_tl_op_past_12m'),
 (0.007314061211727817, 'num_rev_tl_bal_gt_0'),
 (0.007192278119764683, 'percent_bc_gt_75'),
 (0.007125577392678439, 'num_bc_sats'),
 (0.007116880876960344, 'pct_tl_nvr_dlq'),
 (0.006979740382743243, 'open_acc_6m'),
 (0.006533260608495906, 'next_pymnt_d_Apr-2019'),
 (0.006462781142422402, 'inq_fi'),
 (0.00645804615082474, 'mort_acc'),
 (0.0062829888633502695, 'open_rv_12m'),
 (0.00626581235161495, 'issue_d_Jan-2019'),
 (0.006229107578523668, 'open_act_il'),
 (0.005638137842841112, 'tot_coll_amt'),
 (0.0052109648129227614, 'open_il_12m'),
 (0.0045764049475469195, 'issue_d_Feb-2019'),
 (0.004547578767089392, 'inq_last_6mths'),
 (0.0035987223245159358, 'delinq_2yrs'),
 (0.003479385089068314, 'next_pymnt_d_May-2019'),
 (0.003293294957150245, 'pub_rec_bankruptcies'),
 (0.003124706412495215, 'num_accts_ever_120_pd'),
 (0.0028154870408293514, 'pub_rec'),
 (0.002292507131239439, 'verification_status_Not Verified'),
 (0.0022104922516206333, 'verification_status_Source Verified'),
 (0.0021778068100065788, 'application_type_Joint App'),
 (0.002078028254681546, 'application_type_Individual'),
 (0.0020637369763799973, 'home_ownership_MORTGAGE'),
 (0.0020062951308637837, 'verification_status_Verified'),
 (0.0018531764523270964, 'collections_12_mths_ex_med'),
 (0.0018042150695616213, 'home_ownership_RENT'),
 (0.0017475983114175041, 'home_ownership_OWN'),
 (0.0014564011363326598, 'num_tl_90g_dpd_24m'),
 (0.0010519973873884998, 'initial_list_status_w'),
 (0.0007249393531046635, 'initial_list_status_f'),
 (0.0006150480508268, 'home_ownership_ANY'),
 (0.0003214632720670069, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'pymnt_plan'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'hardship_flag'),
 (0.0, 'delinq_amnt'),
 (0.0, 'debt_settlement_flag'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble AdaBoost Classifier

In [17]:
# Train the Classifier
# YOUR CODE HERE
from sklearn.ensemble import AdaBoostClassifier

abc = AdaBoostClassifier(n_estimators=100, random_state=1)

abc_model = abc.fit(X_train, y_train)

abc_pred = abc_model.predict(X_test)

In [18]:
# Calculated the balanced accuracy score
# YOUR CODE HERE

balanced_accuracy_score(y_test, abc_pred)

0.6879726472413378

In [19]:
# Display the confusion matrix
# YOUR CODE HERE

confusion_matrix(y_test, abc_pred)

array([[   38,    63],
       [    5, 17099]], dtype=int64)

In [20]:
# Print the imbalanced classification report
# YOUR CODE HERE

print(classification_report_imbalanced(y_test, abc_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.88      0.38      1.00      0.53      0.61      0.35       101
   low_risk       1.00      1.00      0.38      1.00      0.61      0.40     17104

avg / total       1.00      1.00      0.38      1.00      0.61      0.40     17205